### ISSUE TITLE
How to combine multiple cucumber reports generated from cucumber-jvm-parallel-plugin

### ISSUE THREAD

**Issue by kapilsuri87** [damianszczepanik/maven-cucumber-reporting#117] opened 2018-09-05 08:52 UTC
Hi,

Thanks for the plugin, really appreciate the report details.

Also, this is not an issue just a query to implement reporting plugin,

I do have on question though. Is there a way to combine all the cucumber reports which are being generated by cucumber-jvm-parallel-plugin into one single report?

I have the below configuration for maven-cucumber-reporting and cucumber-jvm-parallel-plugin
cucumber-jvm-parallel-plugin
plugin>
				<groupId>com.github.temyers</groupId>
				<artifactId>cucumber-jvm-parallel-plugin</artifactId>
				<version>5.0.0</version>
				<executions>
					<execution>
						<id>generateRunners</id>
						<phase>validate</phase>
						<goals>
							<goal>generateRunners</goal>
						</goals>
						<configuration>
							
							
							<glue>org/framework/adib/selendroidTestApp/StepDefinition</glue>
							
							
							<outputDirectory>${project.build.directory}/generated-test-sources/${platform}_features
							</outputDirectory>
							
							<featuresDirectory>feature Directory</featuresDirectory>
							
							<cucumberOutputDir>${project.build.directory}/cucumber_reports/
							</cucumberOutputDir>
							
							<format>html,json</format>
							
							<strict>true</strict>
							
							<monochrome>true</monochrome>
							
							<tags>
								<tag>@Prod</tag>
							</tags>

							<namingScheme>pattern</namingScheme>
							
							<namingPattern>{f}_Parallel{c}IT_${platform}</namingPattern>

							
							
							<filterFeaturesByTags>true</filterFeaturesByTags>
						</configuration>
					</execution>
				</executions>
			</plugin>

<plugin>
				<groupId>net.masterthought</groupId>
				<artifactId>maven-cucumber-reporting</artifactId>
				<version>3.20.0</version>
				<executions>
					<execution>
						<id>execution</id>
						<phase>verify</phase>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<projectName>Automation Test Report</projectName>
							<outputDirectory>${project.build.directory}/test-reports</outputDirectory>
							optional, defaults to outputDirectory if not specified
							<inputDirectory>${project.build.directory}/cucumber_reports/</inputDirectory>
							<jsonFiles>
								supports wildcard or name pattern
								<param>**/*.json</param>
							</jsonFiles>
							<cucumberOutput>${project.build.directory}/cucumber.json</cucumberOutput>
							<buildNumber>1</buildNumber>
							<parallelTesting>true</parallelTesting>
						</configuration>
					</execution>
				</executions>
			</plugin>

Any help would be appreciated.

**Comment by damianszczepanik** [comment] 2018-09-09 20:40
Duplicate of https://github.com/jenkinsci/cucumber-reports-plugin/pull/98

**Closed by damianszczepanik** 2018-09-09 20:40 UTC
