### ISSUE TITLE
cucumber report from multiple json generated from parallel doesn't work properly

### ISSUE THREAD

**Issue by prashantd31** [damianszczepanik/maven-cucumber-reporting#64] opened 2017-05-18 00:55 UTC
Hi,

I have been using this library and really appreciate your work.

I am using cucumber html report in conjunction with cucumber-jvm-parallel-plugin from com.github.temyers. 

I have 3 feature files each one has 2 scenarios. All scenarios have same tag ( Say "Smoke" )

Case 1 - Parallel scheme = Feature.  

- I ran mvn test. I see 3 jsons generated at the end of execution
- I generate cucumber report by feeding in jsons. 
- Cucumber report comes fine in dashboard view with 3 feature entries

Case 2 - Parallel scheme = Scenario

- I ran mvn test. I see  6 jsons generated at the end of execution
- I generate cucumber report by feeding in json. 

Problem - For case 2 in the dashboard view of report I see duplicate feature entries. Ideally there should be 3 feature entries (Instead of 6).

Would you please look into this to see possible solution?

**Comment by damianszczepanik** [comment] 2017-05-18 18:54
Did you try https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/Configuration.java#L40 ?

**Comment by prashantd31** [comment] 2017-05-19 01:18
Hi,

Yes i tried setting configuration.setParallelTesting(true) but no luck. I still see same issue

**Comment by damianszczepanik** [comment] 2017-05-19 19:35
Show me JSON files

**Comment by prashantd31** [comment] 2017-05-20 02:37
Attaching json files & screen shot of dashboard
[Json_Files.zip](https://github.com/damianszczepanik/maven-cucumber-reporting/files/1015842/Json_Files.zip)

**Comment by damianszczepanik** [comment] 2017-05-21 16:22
You provided 6 JSON files with features that have same name so your report has same rows even they refer to different results. This is by design.

**Comment by prashantd31** [comment] 2017-05-22 01:03
Thanks. I understand that this is by design. So can we conclude that it is not possible to consolidate report when parallel scheme is "SCENARIO" as the cucumber-parallel plug-in creates
number of test of runner classes = number of json regardless of how many feature files they refer to. Would you please advise how do i generate cucumber html report in this case? We really need to run scenarios in parallel. Would you consider to include such enhancement to support parallel scenario.

**Comment by damianszczepanik** [comment] 2017-05-22 20:18
Looks like this problem https://github.com/jenkinsci/cucumber-reports-plugin/pull/98

**Comment by prashantd31** [comment] 2017-05-23 00:33
Yes. This is exactly what I am looking for. It will be great if you include that. Would you be incorporating this feature for cucumber-reports Jenkins plug in as well?

**Comment by damianszczepanik** [comment] 2017-05-23 06:13
Closing as duplicate.

**Closed by damianszczepanik** 2017-05-23 06:13 UTC

**Comment by telangn** [comment] 2018-08-03 16:12
@prashantd31 can you show how you set up your POM for parallel testing so that the reports could grab all the json files? besides turning on the paralleltesting flag to true, do you have to specify several output and cucumber output directories in the POM?
