### ISSUE TITLE
Embeddings folder is empty

### ISSUE THREAD

**Issue by arkkael** [damianszczepanik/maven-cucumber-reporting#75] opened 2017-10-20 08:37 UTC
Hello! I turned my project into cucumber-jvm-2.0.1 and this plugin stopped to provide screenshots, that embed to,  json has data of it. In classic html reports, that came out of cucumber, embedded0.png is exist, but embeddings folder in maven-reporting-plugin outputDirectory is empty. 
Json(I reduced data output):
```
 {
    "line": 2,
    "elements": [
      {
        "before": [
          {
            "result": {
              "duration": 5872593651,
              "status": "passed"
            },
            "match": {
              "location": "stepDefinition.setUp(Scenario)"
            }
          }
        ],
        "line": 5,
        "name": "Entry check",
        "description": "",
        "id": "xcg;check-entry",
        "after": [
          {
            "result": {
              "duration": 2255644098,
              "status": "passed"
            },
            "match": {
              "location": "stepDefinition.tearDown(Scenario)"
            },
            "embedding": [
              {
                "data": "iVBORw0KGgoAAAANSUhEUgAAB3AAAAO0CAIAAADbKDCgAAAgAElEQVR4nOzdSXMj6Z3g6fd1h2MlyOASERlbbkqpWl0atczK6lSXMisrs+rbtPUXmEN/gDnXqU79Kcb6G8x5DnXRrU5lJpvprEUtZSq32Ddu2OHvHDwCwdgyPSODAEg+j8koBAASTgpy0H/84/UY/sv/CAAAAAAA8EOyVW8AAAAAAABng6AMAAAAAEAtgjIAAAAAALUIygAAAAAA1CIoAwAAAABQi6AMA8VJOfK0cP7zwbT/wEAeFInficAAKDjtoZJFBrrIZ4rrd2f5V24eFNVotDjfDLjyUvknFNVVV1ExvrE/Hx9g8Y3DUBrysrOc19DykalIxPK1rnDeVFa22STMgAAOI1AGQCA51CVXhT4KLxQ0aN5kXdj+slf3wXjyQDQjLyw/i556U7rRVHao3nR9lYAALC+CJQBAHiOYRKFgZ+kVWVvsvp9FyIyzxlPXqbF6PGzZpApuwDWU2ltWlQr33pRCECMoAAAAAAIQIygAAAAAAhAjKAAAAAACECMoAAAAAAIQIygAAAAAAhAjKAAAAAACECMoAAAAAAIQIygAAAAAAhAjKAAAAAACECMoAAAAAAIQIygAAAAAAhAjKAAAAAACECMoAAAAAAIQIygAAAAAAhAjKAAAAAACECMoAAAAAAIQIygAAAAAAhAjKAAAAAACECMoAAAAAAIQIygAAAAAAhAjKAAAAAACECMoAAAAAAIQIygAAAAAAhAjKAAAAAACECMoAAAAAAIQIygAAAAAAhAjKAAAAAACE/H/NATorvL0oWgAAAABJRU5ErkJggg\u003d\u003d",
                "mime_type": "image/png"
              }
            ]
          }
        ],

```
Reports created successfully, but without any screenshots. Plugin version : 3.11.0

**Comment by gauravkarvir** [comment] 2017-10-20 15:25
Thats true even i am facing the same issue with the upgrade

**Comment by damianszczepanik** [comment] 2017-10-20 19:53
Duplicate of https://github.com/damianszczepanik/cucumber-reporting/issues/668

**Closed by damianszczepanik** 2017-10-20 19:53 UTC
